version: "3"

services:
  atcoder-runner:
    user: vscode
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/atcoder-runner:delegated
    working_dir: /atcoder-runner
    tty: true
