version: "3"

services:
  cpp-runner-for-atcoder:
    user: vscode
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/cpp-runner-for-atcoder:delegated
    working_dir: /cpp-runner-for-atcoder
    tty: true
